# Generated by Django 2.1.1 on 2018-09-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['title'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
