# Generated by Django 2.1.1 on 2018-09-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180905_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to='notes', verbose_name='Apuntes'),
        ),
    ]
